### ISSUE TITLE
Error during backup: You cannot remove a running container 

### ISSUE THREAD

**Issue by einarf** [ZettaIO/restic-compose-backup#1]
2019-12-05 02:43:10,059 - INFO: 2019-12-05 02:43:10,058 - INFO: Backing up volumes
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/d4f0ae252fd9d1ed2df99baffcf07c53548404610a0334bc6648b6a04d66dad4?v=False&link=False&force=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rcb", line 11, in <module>
    load_entry_point('restic-compose-backup', 'console_scripts', 'rcb')()
  File "/restic-compose-backup/restic_compose_backup/cli.py", line 35, in main
    backup(config, containers)
  File "/restic-compose-backup/restic_compose_backup/cli.py", line 100, in backup
    "com.docker.compose.project": containers.project_name,
  File "/restic-compose-backup/restic_compose_backup/backup_runner.py", line 57, in run
    container.remove()
  File "/usr/lib/python3.7/site-packages/docker/models/containers.py", line 339, in remove
    return self.client.api.remove_container(self.id, **kwargs)
  File "/usr/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/docker/api/container.py", line 992, in remove_container
    self._raise_for_status(res)
  File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("You cannot remove a running container d4f0ae252fd9d1ed2df99baffcf07c53548404610a0334bc6648b6a04d66dad4. Stop the container before attempting removal or force remove")

**Comment by einarf** [comment]
Fixed in 0.3.1
