### ISSUE TITLE
pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by jwaes** [ZettaIO/restic-compose-backup#42]
With this configuration

```
version: '3'
services:

  backup:
    image: zettaio/restic-compose-backup:0.7.1
    environment:
      - TZ:"Europe/Brussels"
    env_file:
      - restic-backup.env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - cache:/cache
    labels:
      restic-compose-backup.volumes: true 
```     

i get this issue:

```

2024-02-10 08:45:01,696 - DEBUG: Starting backup container with image zettaio/restic-compose-backup:0.7.1
2024-02-10 08:45:01,696 - INFO: Starting backup container
2024-02-10 08:45:02,095 - INFO: Backup process container: exciting_jemison
2024-02-10 08:45:02,187 - INFO: /usr/bin/restic-compose-backup:15: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
2024-02-10 08:45:02,188 - INFO:   from pkg_resources import load_entry_point
2024-02-10 08:45:02,321 - INFO: Traceback (most recent call last):
2024-02-10 08:45:02,322 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 803, in urlopen
2024-02-10 08:45:02,322 - INFO:     **response_kw,
2024-02-10 08:45:02,323 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 505, in _make_request
2024-02-10 08:45:02,323 - INFO:     enforce_content_length=enforce_content_length,
2024-02-10 08:45:02,324 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 395, in request
2024-02-10 08:45:02,324 - INFO:     self.endheaders()
2024-02-10 08:45:02,325 - INFO:   File "/usr/lib/python3.7/http/client.py", line 1272, in endheaders
2024-02-10 08:45:02,325 - INFO:     self._send_output(message_body, encode_chunked=encode_chunked)
2024-02-10 08:45:02,326 - INFO:   File "/usr/lib/python3.7/http/client.py", line 1032, in _send_output
2024-02-10 08:45:02,326 - INFO:     self.send(msg)
2024-02-10 08:45:02,327 - INFO:   File "/usr/lib/python3.7/http/client.py", line 972, in send
2024-02-10 08:45:02,327 - INFO:     self.connect()
2024-02-10 08:45:02,328 - INFO:   File "/usr/lib/python3.7/site-packages/docker/transport/unixconn.py", line 27, in connect
2024-02-10 08:45:02,329 - INFO:     sock.connect(self.unix_socket)
2024-02-10 08:45:02,329 - INFO: FileNotFoundError: [Errno 2] No such file or directory
2024-02-10 08:45:02,329 - INFO: 
2024-02-10 08:45:02,330 - INFO: During handling of the above exception, another exception occurred:
2024-02-10 08:45:02,330 - INFO: 
2024-02-10 08:45:02,331 - INFO: Traceback (most recent call last):
2024-02-10 08:45:02,331 - INFO:   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
2024-02-10 08:45:02,332 - INFO:     chunked=chunked,
2024-02-10 08:45:02,332 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 846, in urlopen
2024-02-10 08:45:02,333 - INFO:     method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
2024-02-10 08:45:02,333 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 470, in increment
2024-02-10 08:45:02,334 - INFO:     raise reraise(type(error), error, _stacktrace)
2024-02-10 08:45:02,334 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/util/util.py", line 38, in reraise
2024-02-10 08:45:02,335 - INFO:     raise value.with_traceback(tb)
2024-02-10 08:45:02,335 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 803, in urlopen
2024-02-10 08:45:02,335 - INFO:     **response_kw,
2024-02-10 08:45:02,336 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 505, in _make_request
2024-02-10 08:45:02,336 - INFO:     enforce_content_length=enforce_content_length,
2024-02-10 08:45:02,337 - INFO:   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 395, in request
2024-02-10 08:45:02,337 - INFO:     self.endheaders()
2024-02-10 08:45:02,338 - INFO:   File "/usr/lib/python3.7/http/client.py", line 1272, in endheaders
2024-02-10 08:45:02,338 - INFO:     self._send_output(message_body, encode_chunked=encode_chunked)
2024-02-10 08:45:02,339 - INFO:   File "/usr/lib/python3.7/http/client.py", line 1032, in _send_output
2024-02-10 08:45:02,339 - INFO:     self.send(msg)
2024-02-10 08:45:02,339 - INFO:   File "/usr/lib/python3.7/http/client.py", line 972, in send
2024-02-10 08:45:02,339 - INFO:     self.connect()
2024-02-10 08:45:02,340 - INFO:   File "/usr/lib/python3.7/site-packages/docker/transport/unixconn.py", line 27, in connect
2024-02-10 08:45:02,340 - INFO:     sock.connect(self.unix_socket)
2024-02-10 08:45:02,341 - INFO: urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
2024-02-10 08:45:02,341 - INFO: 
2024-02-10 08:45:02,341 - INFO: During handling of the above exception, another exception occurred:
2024-02-10 08:45:02,342 - INFO: 
2024-02-10 08:45:02,342 - INFO: Traceback (most recent call last):
2024-02-10 08:45:02,343 - INFO:   File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
2024-02-10 08:45:02,343 - INFO:     return self.version(api_version=False)["ApiVersion"]
2024-02-10 08:45:02,344 - INFO:   File "/usr/lib/python3.7/site-packages/docker/api/daemon.py", line 181, in version
2024-02-10 08:45:02,344 - INFO:     return self._result(self._get(url), json=True)
2024-02-10 08:45:02,345 - INFO:   File "/usr/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
2024-02-10 08:45:02,345 - INFO:     return f(self, *args, **kwargs)
2024-02-10 08:45:02,346 - INFO:   File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 237, in _get
2024-02-10 08:45:02,346 - INFO:     return self.get(url, **self._set_request_timeout(kwargs))
2024-02-10 08:45:02,347 - INFO:   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 602, in get
2024-02-10 08:45:02,347 - INFO:     return self.request("GET", url, **kwargs)
2024-02-10 08:45:02,348 - INFO:   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
2024-02-10 08:45:02,348 - INFO:     resp = self.send(prep, **send_kwargs)
2024-02-10 08:45:02,349 - INFO:   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
2024-02-10 08:45:02,349 - INFO:     r = adapter.send(request, **kwargs)
2024-02-10 08:45:02,350 - INFO:   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 501, in send
2024-02-10 08:45:02,350 - INFO:     raise ConnectionError(err, request=request)
2024-02-10 08:45:02,351 - INFO: requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
2024-02-10 08:45:02,351 - INFO: 
2024-02-10 08:45:02,351 - INFO: During handling of the above exception, another exception occurred:
2024-02-10 08:45:02,351 - INFO: 
2024-02-10 08:45:02,351 - INFO: Traceback (most recent call last):
2024-02-10 08:45:02,352 - INFO:   File "/usr/bin/restic-compose-backup", line 33, in <module>
2024-02-10 08:45:02,353 - INFO:     sys.exit(load_entry_point('restic-compose-backup', 'console_scripts', 'restic-compose-backup')())
2024-02-10 08:45:02,353 - INFO:   File "/restic-compose-backup/restic_compose_backup/cli.py", line 23, in main
2024-02-10 08:45:02,353 - INFO:     containers = RunningContainers()
2024-02-10 08:45:02,354 - INFO:   File "/restic-compose-backup/restic_compose_backup/containers.py", line 353, in __init__
2024-02-10 08:45:02,354 - INFO:     all_containers = utils.list_containers()
2024-02-10 08:45:02,355 - INFO:   File "/restic-compose-backup/restic_compose_backup/utils.py", line 37, in list_containers
2024-02-10 08:45:02,355 - INFO:     client = docker_client()
2024-02-10 08:45:02,356 - INFO:   File "/restic-compose-backup/restic_compose_backup/utils.py", line 27, in docker_client
2024-02-10 08:45:02,356 - INFO:     return docker.from_env()
2024-02-10 08:45:02,357 - INFO:   File "/usr/lib/python3.7/site-packages/docker/client.py", line 101, in from_env
2024-02-10 08:45:02,358 - INFO:     **kwargs_from_env(**kwargs)
2024-02-10 08:45:02,359 - INFO:   File "/usr/lib/python3.7/site-packages/docker/client.py", line 45, in __init__
2024-02-10 08:45:02,359 - INFO:     self.api = APIClient(*args, **kwargs)
2024-02-10 08:45:02,360 - INFO:   File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 197, in __init__
2024-02-10 08:45:02,361 - INFO:     self._version = self._retrieve_server_version()
2024-02-10 08:45:02,361 - INFO:   File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
2024-02-10 08:45:02,362 - INFO:     f'Error while fetching server API version: {e}'
2024-02-10 08:45:02,363 - INFO: docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
2024-02-10 08:45:02,490 - DEBUG: Container ExitCode 1
2024-02-10 08:45:02,533 - INFO: Backup container exit code: 1
2024-02-10 08:45:02,534 - DEBUG: Getting alert backends
2024-02-10 08:45:02,534 - DEBUG: Alert backend 'smtp' configured: False
2024-02-10 08:45:02,534 - DEBUG: Alert backend 'discord_webhook' configured: False
2024-02-10 08:45:02,535 - INFO: No alerts configured
```

**Comment by einarf** [comment]
The `pkg_resources` message is just a warning, but should probably be fixed. The real issue here is reading the socket file mapped into the container for taking with docker.
